### ISSUE TITLE
renamed_element mutates input element

### ISSUE THREAD

**Issue by caspark** [wolfmanstout/dragonfly-commands#2]
Hey James, I noticed this when I was fixing up a bunch of lint errors in my grammar, which I originally based on your grammar - it looks like `renamed_element` is supposed to mutate the copy which it makes, but instead it mutates the input element:

```
def renamed_element(name, element):
    element_copy = copy.copy(element)
    element.name = name
    return element
```

Just thought I'd give you a heads up, in case it saves you time troubleshooting down the line!

**Comment by wolfmanstout** [comment]
Wow, good catch! I guess it works because I also return the original. Looks like a bug waiting to happen; will fix. Thanks!
