### ISSUE TITLE
Is yappi a required dependency? Difficult to install on Windows

### ISSUE THREAD

**Issue by jaanaltosaar** [wolfmanstout/dragonfly-commands#3]
Ran into several issues for `pip install yappi` as in requirements.txt; submitted an issue but seems like it might take time to fix - https://github.com/sumerc/yappi/issues/81#issuecomment-843506185

Which version of MSVC 14.0 is recommended on Windows 10 for natlink/dragonfly/etc?

Just wondering if I might continue the setup despite not being able to install yappi. 

Thanks so much!

**Comment by wolfmanstout** [comment]
yappi is a very optional dependency -- you should be able to just comment out the import and 99% of functionality will work for you. It's only invoked if the user wants to benchmark a command. Sorry to hear that this is causing trouble, I don't remember running into this!

**Comment by jaanaltosaar** [comment]
Awesome, thanks so much!
