### ISSUE TITLE
How to find MacroSystem directory?

### ISSUE THREAD

**Issue by jaanaltosaar** [wolfmanstout/dragonfly-commands#4]
I am naively following the install instructions, and cannot locate the MacroSystem directory. 

Filed an issue under dragonfly describing the circular install instructions: https://github.com/dictation-toolbox/dragonfly/issues/341

(Feel free to close this issue if off-topic! Thank you :)

**Comment by wolfmanstout** [comment]
That just looks like a bad log message in Natlink. You did the right thing to set user directory.

**Comment by jaanaltosaar** [comment]
Hmm, even after setting the user directory, it does not have a MacroSystem directory. Will keep debugging to see where it might be

**Comment by wolfmanstout** [comment]
I'm saying it doesn't matter. You set whatever you want as the user directory and drop your grammars in there. No need to think about MacroSystem at that point.
